Repository mgao08/HelloSudoku, pull requests merged in 2024-04, with the labels that each got.

#18 Game pane UI
  views/css/styles.css
  views/img/favicon.svg
  views/index.html
  views/js/script.js
Labels: UI, JavaScript

#20 Paused & won masks
  views/css/styles.css
  views/index.html
  views/js/script.js
Labels: UI, JavaScript

#21 Merging newest updates to product branch
  models/sudoku/sample.json
  package-lock.json
  package.json
  server/server.js
  views/css/styles.css
  views/img/favicon.svg
  views/index.html
  views/js/script.js
Labels: UI, JavaScript

#25 Better guest access
  views/css/styles.css
  views/index.html
  views/js/script.js
Labels: Enhancement, UI, JavaScript

#26 Implemented API, authentication and authorization. Added .env.sample file
  .env.sample
  controllers/sudokuController.js
  controllers/usersController.js
  middlewares/authorize.js
  models/puzzle.js
  models/user.js
  package-lock.json
  package.json
  server/server.js
  services/sudoku.js
  services/users.js
  utils/crypto.js
  utils/db.js
  utils/env.js
Labels: backend

#27 Backend
  controllers/sudokuController.js
  models/puzzleForADay.js
  server/server.js
  services/sudoku.js
  utils/promise.js
Labels: backend

#28 Updated fillGamePaneGrid
  services/sudoku.js
  views/js/script.js
Labels: sudoku

#29 Updated fillGamePaneGrid
  views/js/script.js
Labels: sudoku

#30 Implemented registration and login functionality on front end
  controllers/usersController.js
  services/users.js
  views/index.html
  views/js/script.js
Labels: JavaScript

#34 Added "searching a user from admin panel"
  middlewares/authorize.js
  views/index.html
  views/js/script.js
Labels: JavaScript

#36 Added "change user role" functionality
  controllers/usersController.js
  middlewares/authorize.js
  services/users.js
  views/js/script.js
Labels: JavaScript, backend

#38 Implemented "delete user from Admin panel"
  controllers/usersController.js
  services/users.js
  views/js/script.js
Labels: JavaScript, backend

#39 Fixed an error fetching the puzzle of the day
  services/sudoku.js
Labels: bug

#49 Implemented records functionality and call them from front-end
  controllers/sudokuController.js
  services/sudoku.js
  views/js/script.js
Labels: JavaScript, backend, sudoku

#51 Added records data in the user search in admin panel
  views/js/script.js
Labels: JavaScript

#57 Updated reset, changed the default page back to dashboard, and deleted unused comments
  controllers/sudokuController.js
  controllers/usersController.js
  services/sudoku.js
  services/users.js
  views/js/script.js
Labels: JavaScript

#65 Registration form validation
  views/index.html
  views/js/script.js
Labels: UI, JavaScript

#66 Implemented admin panel display search result and export user data features
  views/index.html
  views/js/script.js
Labels: UI, JavaScript

#68 Implemented logger middleware
  middlewares/logger.js
  server/server.js
  services/sudoku.js
Labels: backend, Database

#69 Includes all the polishing works in issue #67
  views/css/styles.css
  views/index.html
  views/js/script.js
Labels: bug, Enhancement, UI, JavaScript

#70 Update product branch with latest updates
  .editorconfig
  .env.sample
  controllers/sudokuController.js
  controllers/usersController.js
  middlewares/authorize.js
  middlewares/logger.js
  models/puzzle.js
  models/puzzleForADay.js
  models/user.js
  package-lock.json
  package.json
  server/server.js
  services/sudoku.js
  services/users.js
  utils/crypto.js
  utils/db.js
  utils/env.js
  utils/promise.js
  views/css/styles.css
  views/index.html
  views/js/script.js
Labels: Enhancement, backend, sudoku
